# Generated by Django 5.2.6 on 2026-01-17 16:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0009_alter_client_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre del plan (ej: 'Plan Pro')", max_length=50)),
                ('slug', models.SlugField(help_text="Identificador URL (ej: 'pro')", unique=True)),
                ('price', models.DecimalField(decimal_places=0, help_text='Precio en CLP (pago único inicial)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('renewal_price', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Precio mensual de renovación (futuro)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tagline', models.CharField(blank=True, help_text="Subtítulo corto (ej: 'Ideal para emprendedores')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción completa para landing page')),
                ('features', models.JSONField(blank=True, default=list, help_text='Lista de características incluidas (JSON array)')),
                ('available_themes', models.JSONField(blank=True, default=list, help_text='Temas disponibles para este plan (JSON array de slugs)')),
                ('max_pages', models.IntegerField(default=5, help_text='Máximo de páginas permitidas')),
                ('max_services', models.IntegerField(default=10, help_text='Máximo de servicios en catálogo')),
                ('max_images', models.IntegerField(default=50, help_text='Máximo de imágenes en Cloudinary')),
                ('max_storage_mb', models.IntegerField(default=100, help_text='Almacenamiento máximo en MB')),
                ('has_custom_domain', models.BooleanField(default=False, help_text='¿Permite dominio personalizado?')),
                ('has_analytics', models.BooleanField(default=False, help_text='¿Incluye analytics avanzados?')),
                ('has_priority_support', models.BooleanField(default=False, help_text='¿Incluye soporte prioritario?')),
                ('has_white_label', models.BooleanField(default=False, help_text='¿Sin marca Andesscale?')),
                ('is_active', models.BooleanField(default=True, help_text='¿Visible en página de precios?')),
                ('is_featured', models.BooleanField(default=False, help_text='¿Destacar como recomendado?')),
                ('display_order', models.IntegerField(default=0, help_text='Orden de aparición (menor = primero)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador público de la orden', primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, help_text='Número de orden legible (ej: ORD-2024-0001)', max_length=20, unique=True)),
                ('email', models.EmailField(help_text='Email del comprador', max_length=254)),
                ('buyer_name', models.CharField(blank=True, help_text='Nombre del comprador', max_length=100)),
                ('buyer_phone', models.CharField(blank=True, help_text='Teléfono del comprador', max_length=20)),
                ('billing_rut', models.CharField(blank=True, help_text='RUT para facturación (ej: 12.345.678-9)', max_length=12)),
                ('billing_razon_social', models.CharField(blank=True, help_text='Razón social o nombre', max_length=200)),
                ('billing_giro', models.CharField(blank=True, help_text='Giro comercial', max_length=200)),
                ('billing_direccion', models.CharField(blank=True, help_text='Dirección fiscal', max_length=300)),
                ('billing_comuna', models.CharField(blank=True, help_text='Comuna', max_length=100)),
                ('amount', models.DecimalField(decimal_places=0, help_text='Monto pagado en CLP', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='CLP', help_text='Moneda del pago', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Pago'), ('processing', 'Procesando Pago'), ('paid', 'Pagado - Pendiente Onboarding'), ('onboarding', 'En Proceso de Onboarding'), ('completed', 'Completado'), ('failed', 'Pago Fallido'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('expired', 'Token Expirado')], db_index=True, default='pending', help_text='Estado actual de la orden', max_length=20)),
                ('mp_payment_id', models.CharField(blank=True, db_index=True, help_text='ID del pago en Mercado Pago', max_length=50)),
                ('mp_status', models.CharField(blank=True, help_text='Estado del pago en MP (approved, pending, rejected, etc)', max_length=50)),
                ('mp_status_detail', models.CharField(blank=True, help_text='Detalle del estado en MP', max_length=100)),
                ('mp_payment_method', models.CharField(blank=True, help_text='Método de pago usado (credit_card, debit_card, etc)', max_length=50)),
                ('mp_payment_type', models.CharField(blank=True, help_text='Tipo de pago (credit_card, bank_transfer, etc)', max_length=50)),
                ('mp_response_data', models.JSONField(blank=True, default=dict, help_text='Respuesta completa de Mercado Pago (JSON)')),
                ('onboarding_token', models.UUIDField(blank=True, help_text='Token único para acceso a onboarding', null=True, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración del token', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la orden')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Fecha/hora del pago exitoso', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Fecha/hora de finalización del onboarding', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha de expiración de la orden (si no se paga)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas internas (no visibles al cliente)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP del comprador', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User Agent del navegador')),
                ('client', models.ForeignKey(blank=True, help_text='Tenant creado (post-onboarding)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tenants.client')),
                ('plan', models.ForeignKey(help_text='Plan contratado', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.plan')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Acción realizada (create, approve, reject, refund, etc)', max_length=50)),
                ('mp_payment_id', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('status_detail', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Datos crudos del evento')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='orders.order')),
            ],
            options={
                'verbose_name': 'Log de Pago',
                'verbose_name_plural': 'Logs de Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email'], name='orders_orde_email_88c705_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['mp_payment_id'], name='orders_orde_mp_paym_5fb890_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['onboarding_token'], name='orders_orde_onboard_599ffd_idx'),
        ),
    ]
