# Generated by Django 5.2.6 on 2026-08-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('from_email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField()),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido (máximo de reintentos alcanzado)')], db_index=True, default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email en cola',
                'verbose_name_plural': 'Emails en cola',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_emailo_status_e850d2_idx')],
            },
        ),
    ]
