# Generated by Django 5.2.6 on 2025-12-01 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre interno del cliente (ej: 'Servelec Ingeniería')", max_length=100)),
                ('slug', models.SlugField(help_text="Identificador único generado automáticamente (ej: 'servelec-ingenieria')", max_length=100, unique=True)),
                ('domain', models.CharField(db_index=True, help_text="Dominio completo sin https:// (ej: 'servelec-ingenieria.cl')", max_length=100, unique=True)),
                ('company_name', models.CharField(help_text='Nombre legal/comercial de la empresa', max_length=200)),
                ('contact_email', models.EmailField(help_text='Email principal de contacto del cliente', max_length=254)),
                ('contact_phone', models.CharField(help_text='Teléfono de contacto (ej: +56912345678)', max_length=20)),
                ('template', models.CharField(choices=[('electricidad', 'Electricidad/Servicios Técnicos'), ('construccion', 'Construcción'), ('servicios_profesionales', 'Servicios Profesionales'), ('portafolio', 'Portafolio Personal'), ('custom', 'Personalizado')], default='custom', help_text='Template base aplicado a este cliente', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Si está inactivo, el sitio mostrará mensaje de mantenimiento')),
                ('setup_completed', models.BooleanField(default=False, help_text='Marca cuando el cliente complete su configuración inicial')),
                ('setup_fee_paid', models.BooleanField(default=False, help_text='¿El cliente pagó el fee de setup inicial?')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=80.0, help_text='Tarifa mensual en USD (default: $80)', max_digits=6)),
                ('last_payment_date', models.DateField(blank=True, help_text='Fecha del último pago mensual recibido', null=True)),
                ('next_payment_due', models.DateField(blank=True, help_text='Fecha del próximo pago esperado', null=True)),
                ('max_images', models.IntegerField(default=100, help_text='Cantidad máxima de imágenes permitidas en Cloudinary')),
                ('max_pages', models.IntegerField(default=10, help_text='Cantidad máxima de páginas/secciones permitidas')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del cliente')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('notes', models.TextField(blank=True, help_text='Notas internas sobre el cliente (no visible para él)')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain'], name='tenants_cli_domain_420a5e_idx'), models.Index(fields=['is_active'], name='tenants_cli_is_acti_9a4d57_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Color primario en formato HEX (ej: #3B82F6)', max_length=7)),
                ('secondary_color', models.CharField(default='#1E40AF', help_text='Color secundario en formato HEX', max_length=7)),
                ('font_family', models.CharField(default='Inter, sans-serif', help_text="Familia de fuente CSS (ej: 'Roboto, sans-serif')", max_length=100)),
                ('meta_title', models.CharField(blank=True, help_text='Título SEO (máx 60 caracteres)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='Descripción SEO (máx 160 caracteres)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Keywords separadas por comas', max_length=255)),
                ('google_analytics_id', models.CharField(blank=True, help_text='ID de Google Analytics (ej: G-XXXXXXXXXX)', max_length=50)),
                ('facebook_pixel_id', models.CharField(blank=True, help_text='ID de Facebook Pixel', max_length=50)),
                ('facebook_url', models.URLField(blank=True, help_text='URL completa de Facebook (ej: https://facebook.com/empresa)')),
                ('instagram_url', models.URLField(blank=True, help_text='URL completa de Instagram')),
                ('twitter_url', models.URLField(blank=True, help_text='URL completa de Twitter/X')),
                ('linkedin_url', models.URLField(blank=True, help_text='URL completa de LinkedIn')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Número WhatsApp con código país (ej: +56912345678)', max_length=20)),
                ('enable_blog', models.BooleanField(default=False, help_text='Habilitar módulo de blog')),
                ('enable_ecommerce', models.BooleanField(default=False, help_text='Habilitar e-commerce básico')),
                ('enable_multilanguage', models.BooleanField(default=False, help_text='Habilitar soporte multi-idioma')),
                ('client', models.OneToOneField(help_text='Cliente al que pertenecen estas configuraciones', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.client')),
            ],
            options={
                'verbose_name': 'Configuración del Cliente',
                'verbose_name_plural': 'Configuraciones de Clientes',
            },
        ),
    ]
