# Generated by Django 5.2.6 on 2025-12-25 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, help_text='Dominio completo (ej: cliente.tuapp.cl o www.cliente.com)', max_length=255, unique=True)),
                ('domain_type', models.CharField(choices=[('subdomain', 'Subdominio (*.tuapp.cl)'), ('custom', 'Dominio Personalizado')], default='subdomain', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='¿Es el dominio principal? (usado en emails, SEO, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='¿Está activo este dominio?')),
                ('ssl_enabled', models.BooleanField(default=True, help_text='¿SSL configurado?')),
                ('is_verified', models.BooleanField(default=False, help_text='¿Dominio verificado? (DNS configurado)')),
                ('verification_token', models.CharField(blank=True, help_text='Token para verificación DNS', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dominio',
                'verbose_name_plural': 'Dominios',
                'ordering': ['-is_primary', 'domain'],
            },
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='tenants_cli_domain_420a5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='tenants_cli_is_acti_9a4d57_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='clientsettings',
            name='enable_ecommerce',
        ),
        migrations.RemoveField(
            model_name='clientsettings',
            name='enable_multilanguage',
        ),
        migrations.AddField(
            model_name='client',
            name='max_services',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='company_name',
            field=models.CharField(blank=True, help_text='Nombre a mostrar en el sitio', max_length=200),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='enable_contact_form',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='enable_testimonials',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='clients/favicons/'),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/logos/'),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='social_media',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, help_text='Nombre legal/comercial de la empresa', max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email principal de contacto', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si está inactivo, muestra mensaje de mantenimiento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='max_images',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='max_pages',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tarifa mensual en CLP', max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='next_payment_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas internas'),
        ),
        migrations.AlterField(
            model_name='client',
            name='setup_completed',
            field=models.BooleanField(default=False, help_text='¿Completó la configuración inicial?'),
        ),
        migrations.AlterField(
            model_name='client',
            name='setup_fee_paid',
            field=models.BooleanField(default=False, help_text='¿Pagó el fee de setup?'),
        ),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(help_text="Identificador único (ej: 'servelec-ingenieria')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='template',
            field=models.CharField(choices=[('electricidad', 'Electricidad/Servicios Técnicos'), ('construccion', 'Construcción'), ('servicios_profesionales', 'Servicios Profesionales'), ('portafolio', 'Portafolio Personal'), ('custom', 'Personalizado')], default='custom', help_text='Template base aplicado', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.client'),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='enable_blog',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='font_family',
            field=models.CharField(default='Inter, sans-serif', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='primary_color',
            field=models.CharField(default='#2563eb', help_text='Color primario HEX', max_length=7),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='secondary_color',
            field=models.CharField(default='#1e40af', help_text='Color secundario HEX', max_length=7),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='domain',
            name='client',
            field=models.ForeignKey(help_text='Cliente al que pertenece este dominio', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.client'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['domain'], name='tenants_dom_domain_6df599_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['client', 'is_active'], name='tenants_dom_client__8abcfd_idx'),
        ),
    ]
