# Generated by Django 5.2.6 on 2026-01-02 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_domain_remove_client_tenants_cli_domain_420a5e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('none', 'Sin email (solo dashboard)'), ('smtp', 'SMTP personalizado'), ('sendgrid', 'SendGrid'), ('resend', 'Resend'), ('mailgun', 'Mailgun'), ('ses', 'Amazon SES')], default='none', help_text='Proveedor de email a utilizar', max_length=20)),
                ('notify_mode', models.CharField(choices=[('dashboard', 'Solo dashboard'), ('email', 'Solo email'), ('both', 'Dashboard + Email')], default='dashboard', help_text='Cómo notificar nuevos contactos', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='¿Está activo el envío de emails?')),
                ('smtp_host', models.CharField(blank=True, help_text='Servidor SMTP (ej: smtp.zoho.com)', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='Puerto SMTP (587 para TLS, 465 para SSL)')),
                ('smtp_username', models.CharField(blank=True, help_text='Usuario SMTP', max_length=255)),
                ('smtp_password', models.CharField(blank=True, help_text='Contraseña SMTP (se almacena encriptada)', max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Usar TLS (recomendado)')),
                ('smtp_use_ssl', models.BooleanField(default=False, help_text='Usar SSL (alternativa a TLS)')),
                ('api_key', models.CharField(blank=True, help_text='API Key para SendGrid, Resend, etc.', max_length=255)),
                ('from_email', models.EmailField(blank=True, help_text='Email remitente (ej: contacto@empresa.cl)', max_length=254)),
                ('from_name', models.CharField(blank=True, help_text="Nombre del remitente (ej: 'Servelec Ingeniería')", max_length=100)),
                ('reply_to', models.EmailField(blank=True, help_text='Email para respuestas (si es diferente del remitente)', max_length=254)),
                ('notify_emails', models.TextField(blank=True, help_text='Emails a notificar (uno por línea). Si está vacío, usa contact_email del cliente.')),
                ('email_subject_template', models.CharField(default='Nuevo contacto de {name}', help_text='Asunto del email. Variables: {name}, {email}, {subject}', max_length=200)),
                ('send_copy_to_sender', models.BooleanField(default=False, help_text='¿Enviar copia al remitente del formulario?')),
                ('test_mode', models.BooleanField(default=False, help_text='Modo prueba: loguea pero no envía emails')),
                ('last_test_at', models.DateTimeField(blank=True, help_text='Última prueba de conexión', null=True)),
                ('last_test_success', models.BooleanField(default=False, help_text='¿Última prueba exitosa?')),
                ('last_test_error', models.TextField(blank=True, help_text='Error de la última prueba')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='tenants.client')),
            ],
            options={
                'verbose_name': 'Configuración de Email',
                'verbose_name_plural': 'Configuraciones de Email',
            },
        ),
    ]
