# Generated by Django 5.2.6 on 2026-01-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_clientemailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='primary_color',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='secondary_color',
            field=models.CharField(default='#1E40AF', max_length=7),
        ),
    ]
