# Generated by Django 5.2.6 on 2026-01-08 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_clientsettings_description_clientsettings_tagline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_label', models.CharField(default='Nombre completo', help_text='Etiqueta del campo nombre', max_length=50)),
                ('name_placeholder', models.CharField(blank=True, default='Tu nombre', max_length=100)),
                ('email_label', models.CharField(default='Email', max_length=50)),
                ('email_placeholder', models.CharField(blank=True, default='tu@email.com', max_length=100)),
                ('message_label', models.CharField(default='Mensaje', max_length=50)),
                ('message_placeholder', models.CharField(blank=True, default='¿En qué podemos ayudarte?', max_length=200)),
                ('message_rows', models.IntegerField(default=4, help_text='Número de filas del textarea')),
                ('show_phone', models.BooleanField(default=True, help_text='Mostrar campo teléfono')),
                ('phone_required', models.BooleanField(default=False, help_text='¿Es obligatorio?')),
                ('phone_label', models.CharField(default='Teléfono', max_length=50)),
                ('phone_placeholder', models.CharField(blank=True, default='+56 9 1234 5678', max_length=100)),
                ('show_company', models.BooleanField(default=False, help_text='Mostrar campo empresa')),
                ('company_required', models.BooleanField(default=False)),
                ('company_label', models.CharField(default='Empresa', max_length=50)),
                ('company_placeholder', models.CharField(blank=True, default='Tu empresa', max_length=100)),
                ('show_subject', models.BooleanField(default=True, help_text='Mostrar selector de asunto')),
                ('subject_required', models.BooleanField(default=False)),
                ('subject_label', models.CharField(default='Asunto', max_length=50)),
                ('subject_options', models.TextField(default='Consulta general\nSolicitar cotización\nSoporte técnico\nOtro', help_text='Opciones del dropdown, una por línea')),
                ('show_address', models.BooleanField(default=False, help_text='Mostrar campo dirección')),
                ('address_required', models.BooleanField(default=False)),
                ('address_label', models.CharField(default='Dirección', max_length=50)),
                ('address_placeholder', models.CharField(blank=True, default='Tu dirección', max_length=100)),
                ('show_city', models.BooleanField(default=False, help_text='Mostrar campo ciudad')),
                ('city_required', models.BooleanField(default=False)),
                ('city_label', models.CharField(default='Ciudad/Comuna', max_length=50)),
                ('city_placeholder', models.CharField(blank=True, default='', max_length=100)),
                ('show_budget', models.BooleanField(default=False, help_text='Mostrar selector de presupuesto')),
                ('budget_required', models.BooleanField(default=False)),
                ('budget_label', models.CharField(default='Presupuesto estimado', max_length=50)),
                ('budget_options', models.TextField(blank=True, default='Menos de $100.000\n$100.000 - $500.000\n$500.000 - $1.000.000\nMás de $1.000.000\nNo definido', help_text='Opciones del dropdown, una por línea')),
                ('show_urgency', models.BooleanField(default=False, help_text='Mostrar selector de urgencia')),
                ('urgency_required', models.BooleanField(default=False)),
                ('urgency_label', models.CharField(default='Urgencia', max_length=50)),
                ('urgency_options', models.TextField(blank=True, default='Normal\nUrgente\nMuy urgente (24h)', help_text='Opciones del dropdown, una por línea')),
                ('show_source', models.BooleanField(default=False, help_text='Mostrar ¿Cómo nos conociste?')),
                ('source_required', models.BooleanField(default=False)),
                ('source_label', models.CharField(default='¿Cómo nos conociste?', max_length=50)),
                ('source_options', models.TextField(blank=True, default='Google\nRedes sociales\nRecomendación\nOtro', help_text='Opciones del dropdown, una por línea')),
                ('submit_button_text', models.CharField(default='Enviar mensaje', help_text='Texto del botón de envío', max_length=50)),
                ('success_message', models.TextField(default='¡Gracias por contactarnos! Te responderemos a la brevedad.', help_text='Mensaje mostrado después de enviar')),
                ('privacy_text', models.CharField(blank=True, default='Al enviar, aceptas nuestra política de privacidad.', help_text='Texto de privacidad bajo el botón', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_config', to='tenants.client')),
            ],
            options={
                'verbose_name': 'Configuración de Formulario',
                'verbose_name_plural': 'Configuraciones de Formularios',
            },
        ),
    ]
