# Generated by Django 5.2.6 on 2026-01-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_formconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='logo_footer',
            field=models.ImageField(blank=True, help_text='Logo alternativo para el footer, preferiblemente en blanco', null=True, upload_to='clients/logos/', verbose_name='Logo footer (blanco)'),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='clients/favicons/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/logos/', verbose_name='Logo principal'),
        ),
    ]
