# Generated by Django 5.2.6 on 2026-01-13 04:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_clientsettings_logo_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsettings',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo principal'),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='logo_footer',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Logo alternativo para el footer', max_length=255, null=True, verbose_name='Logo footer (blanco)'),
        ),
    ]
