# Generated by Django 5.2.6 on 2026-01-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_clientsettings_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.CharField(choices=[('essential', 'Plan Básico (Solo tema default)'), ('pro', 'Plan Pro (Selección de temas + Logo)'), ('enterprise', 'Plan Enterprise (Diseño a medida)')], default='basic', help_text='Nivel de suscripción del cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email principal', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Teléfono', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='setup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='setup_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='template',
            field=models.CharField(choices=[('default', 'Tema Base (Lanzamiento Rápido)'), ('electricidad', 'Electricidad (Servelec)'), ('industrial', 'Industrial / Maquinaria')], default='default', help_text='Carpeta del tema visual a utilizar', max_length=50),
        ),
    ]
