# Generated by Django 5.2.6 on 2026-01-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_client_plan_alter_client_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='plan',
            field=models.CharField(choices=[('essential', 'Plan Básico (Solo tema default)'), ('pro', 'Plan Pro (Selección de temas + Logo)'), ('enterprise', 'Plan Enterprise (Diseño a medida)')], default='essential', help_text='Nivel de suscripción del cliente', max_length=20),
        ),
    ]
