# Generated by Django 5.2.6 on 2026-03-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_clientsettings_digest_purge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsettings',
            name='auto_purge_enabled',
            field=models.BooleanField(default=False, help_text='Eliminar mensajes leídos/respondidos antiguos automáticamente'),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='digest_frequency',
            field=models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal')], default='weekly', help_text='Con qué frecuencia enviar el resumen (lunes para semanal)', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='inbox_retention_days',
            field=models.PositiveIntegerField(default=30, help_text='Días a retener mensajes antes de purgar (mínimo 7)'),
        ),
    ]
