# Generated by Django 5.2.6 on 2026-03-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_alter_clientsettings_auto_purge_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='enable_gallery',
            field=models.BooleanField(default=False, help_text='Activa el módulo de galería para este cliente. Una vez activado, el cliente puede subir imágenes desde su dashboard.', verbose_name='Galería de imágenes'),
        ),
    ]
