# Generated by Django 5.2.6 on 2026-04-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_add_enable_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='gallery_images_limit',
            field=models.PositiveIntegerField(default=20, help_text='Máximo de imágenes que el cliente puede subir a la galería.', verbose_name='Límite de imágenes de galería'),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='hero_images_limit',
            field=models.PositiveIntegerField(default=3, help_text='Máximo de imágenes que el cliente puede subir para la portada. La imagen default no cuenta dentro de este límite.', verbose_name='Límite de imágenes de portada'),
        ),
        migrations.AlterField(
            model_name='clientsettings',
            name='enable_gallery',
            field=models.BooleanField(default=False, help_text='Activa el módulo de imágenes (portada y galería) para este cliente.', verbose_name='Galería de imágenes'),
        ),
    ]
