# Generated by Django 5.2.6 on 2026-04-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_add_gallery_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='show_default_hero',
            field=models.BooleanField(default=True, help_text='Muestra el hero por defecto junto a las imágenes del cliente. Si está desactivado, solo se muestran las imágenes subidas.', verbose_name='Mostrar diseño base en portada'),
        ),
    ]
