# Generated by Django 5.2.6 on 2026-08-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_clientsettings_add_show_default_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mode_under_construction',
            field=models.BooleanField(default=False, help_text="Si está activo, sirve la página temporal 'En construcción' en lugar del sitio."),
        ),
        migrations.AlterField(
            model_name='client',
            name='template',
            field=models.CharField(choices=[('themes/default', 'Tema Base (Servicios Profesionales)'), ('servelec', 'Electricidad (Servelec)'), ('themes/industrial', 'Industrial / Maquinaria')], default='default', help_text='Carpeta del tema visual a utilizar', max_length=50),
        ),
    ]
