# Generated by Django 5.2.6 on 2026-08-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_client_mode_under_construction_alter_client_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='template',
            field=models.CharField(choices=[('themes/default', 'Tema Base (Servicios Profesionales)'), ('servelec', 'Electricidad (Servelec)')], default='themes/default', help_text='Carpeta del tema visual a utilizar', max_length=50),
        ),
    ]
