# Generated by Django 5.2.6 on 2026-08-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_alter_client_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='template',
            field=models.CharField(choices=[('themes/default', 'Tema Base (Servicios Profesionales)'), ('servelec', 'Electricidad (Servelec)'), ('ranchocachimba', 'Rancho Cachimba (Turismo Rural)')], default='themes/default', help_text='Carpeta del tema visual a utilizar', max_length=50),
        ),
    ]
