# Generated by Django 5.2.6 on 2026-08-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_alter_client_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='accent_color',
            field=models.CharField(default='#F59E0B', max_length=7),
        ),
    ]
