# Generated by Django 5.2.6 on 2026-08-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_client_mode_under_construction_alter_client_template'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['client', 'is_primary', 'is_active'], name='tenants_dom_client__abf870_idx'),
        ),
    ]
