# Generated by Django 5.2.6 on 2026-08-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_domain_tenants_dom_client__abf870_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsettings',
            name='font_family',
            field=models.CharField(choices=[('Inter', 'Inter'), ('Outfit', 'Outfit'), ('Fraunces', 'Fraunces'), ('Space Grotesk', 'Space Grotesk')], default='Inter', max_length=100),
        ),
    ]
