# Generated by Django 5.2.6 on 2026-08-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0022_clientsettings_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='navbar_cta_text',
            field=models.CharField(blank=True, default='', help_text='Texto del botón CTA del navbar (vacío = sin botón)', max_length=60),
        ),
        migrations.AddField(
            model_name='clientsettings',
            name='navbar_cta_url',
            field=models.CharField(blank=True, default='', help_text="Destino del CTA: URL o ancla (ej: '#contacto')", max_length=255),
        ),
    ]
