# Generated by Django 5.2.6 on 2026-08-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0023_clientsettings_navbar_cta_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='template',
            field=models.CharField(choices=[('themes/default', 'Tema Base (Servicios Profesionales)'), ('themes/servelec', 'Electricidad (Servelec)')], default='themes/default', help_text='Carpeta del tema visual a utilizar', max_length=50),
        ),
    ]
