# Generated by Django 5.2.6 on 2026-03-20 03:08

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_add_google_verification_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoconfig',
            name='bing_site_verification',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bing Site Verification'),
        ),
        migrations.AlterField(
            model_name='seoconfig',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Opcional. Usar si esta página tiene duplicados.', verbose_name='URL Canónica'),
        ),
        migrations.AlterField(
            model_name='seoconfig',
            name='google_site_verification',
            field=models.CharField(blank=True, help_text="Método 1: Solo el valor del content. Ej: si Google te da content='abc123', escribe solo 'abc123'.", max_length=100, verbose_name='Google Verification (meta tag)'),
        ),
        migrations.AlterField(
            model_name='seoconfig',
            name='google_verification_file',
            field=models.CharField(blank=True, help_text="Método 2: Solo el código sin 'google' ni '.html'. Ej: si Google te da 'google1a2b3c4d.html', escribe solo '1a2b3c4d'. Genera la URL: /google1a2b3c4d.html", max_length=100, verbose_name='Google Verification (archivo HTML)'),
        ),
        migrations.AlterField(
            model_name='seoconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='seoconfig',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Recomendado: 120–160 caracteres.', max_length=160, validators=[django.core.validators.MaxLengthValidator(160)], verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='seoconfig',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Separadas por comas.', max_length=255, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='seoconfig',
            name='og_description',
            field=models.TextField(blank=True, max_length=200, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='seoconfig',
            name='og_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Tamaño recomendado: 1200x630px.', max_length=255, null=True, verbose_name='OG Image'),
        ),
        migrations.AlterField(
            model_name='seoconfig',
            name='og_title',
            field=models.CharField(blank=True, help_text='Título al compartir en redes sociales.', max_length=95, verbose_name='OG Title'),
        ),
        migrations.AlterField(
            model_name='seoconfig',
            name='schema_json',
            field=models.JSONField(blank=True, help_text='Personalizado. Se genera automáticamente si dejas vacío.', null=True, verbose_name='Schema JSON-LD'),
        ),
        migrations.AlterField(
            model_name='seoconfig',
            name='schema_type',
            field=models.CharField(blank=True, choices=[('', 'Sin Schema'), ('LocalBusiness', 'Local Business'), ('Organization', 'Organización'), ('Service', 'Servicio'), ('ProfessionalService', 'Servicio Profesional'), ('Electrician', 'Electricista'), ('GeneralContractor', 'Contratista'), ('Plumber', 'Gasfiter')], default='', help_text='Permite rich snippets en Google.', max_length=50, verbose_name='Tipo de Schema'),
        ),
        migrations.AlterField(
            model_name='seoconfig',
            name='title',
            field=models.CharField(blank=True, help_text='Recomendado: 50–70 caracteres.', max_length=70, validators=[django.core.validators.MaxLengthValidator(70)], verbose_name='Title (SEO)'),
        ),
    ]
