# Generated by Django 5.2.6 on 2025-12-05 14:26

import ckeditor.fields
import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación (automático)', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización (automático)', verbose_name='Actualizado')),
                ('name', models.CharField(help_text='Nombre completo del visitante', max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(help_text='Email de contacto del visitante', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Teléfono de contacto (opcional)', max_length=20, verbose_name='Teléfono')),
                ('subject', models.CharField(blank=True, help_text='Asunto del mensaje (opcional)', max_length=200, verbose_name='Asunto')),
                ('message', models.TextField(help_text='Mensaje completo del visitante', verbose_name='Mensaje')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se envió el formulario', verbose_name='Fecha de Envío')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del visitante (para seguridad)', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Navegador y sistema operativo del visitante', verbose_name='User Agent')),
                ('is_read', models.BooleanField(default=False, help_text='Marca como leído cuando el cliente lo revise', verbose_name='Leído')),
                ('is_spam', models.BooleanField(default=False, help_text='Marca como spam si es un mensaje no deseado', verbose_name='Spam')),
                ('replied_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se respondió al cliente (opcional)', null=True, verbose_name='Respondido')),
                ('notes', models.TextField(blank=True, help_text='Notas privadas sobre este contacto (no visibles para el visitante)', verbose_name='Notas Internas')),
                ('client', models.ForeignKey(help_text='Cliente al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Formulario de Contacto',
                'verbose_name_plural': 'Formularios de Contacto',
                'ordering': ['client', '-submitted_at'],
                'indexes': [models.Index(fields=['client', 'is_read', 'is_spam'], name='website_con_client__0cd751_idx'), models.Index(fields=['client', '-submitted_at'], name='website_con_client__0a444c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación (automático)', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización (automático)', verbose_name='Actualizado')),
                ('section_type', models.CharField(choices=[('hero', 'Hero / Banner Principal'), ('about', 'Sobre Nosotros'), ('services', 'Servicios'), ('portfolio', 'Portafolio / Proyectos'), ('testimonials', 'Testimonios'), ('team', 'Equipo'), ('contact', 'Contacto'), ('cta', 'Llamada a la Acción'), ('footer', 'Pie de Página'), ('custom', 'Sección Personalizada')], help_text='Tipo de sección de la página', max_length=50, verbose_name='Tipo de Sección')),
                ('title', models.CharField(help_text='Título principal de la sección', max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, help_text='Subtítulo o descripción corta (opcional)', max_length=300, verbose_name='Subtítulo')),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='Contenido HTML enriquecido (opcional)', verbose_name='Contenido')),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Imagen principal de la sección (se guarda en Cloudinary)', max_length=255, null=True, verbose_name='section_image')),
                ('background_image', cloudinary.models.CloudinaryField(blank=True, help_text='Imagen de fondo para la sección (opcional)', max_length=255, null=True, verbose_name='section_bg')),
                ('cta_text', models.CharField(blank=True, help_text='Texto del botón de acción (ej: "Contáctanos", "Ver más")', max_length=100, verbose_name='Texto del Botón')),
                ('cta_url', models.CharField(blank=True, help_text='URL a la que dirige el botón (ej: /contacto, https://wa.me/...)', max_length=200, verbose_name='URL del Botón')),
                ('is_active', models.BooleanField(default=True, help_text='Si está inactivo, no se mostrará en el sitio', verbose_name='Activo')),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición (menor = primero). Ej: 0, 10, 20, 30...', verbose_name='Orden')),
                ('client', models.ForeignKey(help_text='Cliente al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['client', 'order', 'section_type'],
                'indexes': [models.Index(fields=['client', 'section_type', 'is_active'], name='website_sec_client__e9cd13_idx'), models.Index(fields=['client', 'order'], name='website_sec_client__3bc1a3_idx')],
                'unique_together': {('client', 'section_type')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación (automático)', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización (automático)', verbose_name='Actualizado')),
                ('name', models.CharField(help_text='Nombre del servicio (ej: "Instalaciones Eléctricas")', max_length=150, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(help_text='Descripción detallada del servicio (HTML enriquecido)', verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Clase de icono Font Awesome o Lucide (ej: "fa-bolt", "lucide-zap")', max_length=50, verbose_name='Clase de Icono')),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Imagen del servicio (alternativa al icono)', max_length=255, null=True, verbose_name='service_image')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio del servicio en moneda local (opcional)', max_digits=10, null=True, verbose_name='Precio')),
                ('price_label', models.CharField(blank=True, default='Desde', help_text='Texto antes del precio (ej: "Desde", "Por proyecto")', max_length=50, verbose_name='Etiqueta del Precio')),
                ('is_featured', models.BooleanField(default=False, help_text='Si está marcado, se mostrará primero o con estilo especial', verbose_name='Destacado')),
                ('is_active', models.BooleanField(default=True, help_text='Si está inactivo, no se mostrará en el sitio', verbose_name='Activo')),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición (menor = primero)', verbose_name='Orden')),
                ('client', models.ForeignKey(help_text='Cliente al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['client', 'order', '-is_featured', 'name'],
                'indexes': [models.Index(fields=['client', 'is_active', 'is_featured'], name='website_ser_client__16fef8_idx'), models.Index(fields=['client', 'order'], name='website_ser_client__4b6e77_idx')],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación (automático)', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización (automático)', verbose_name='Actualizado')),
                ('client_name', models.CharField(help_text='Nombre de la persona que da el testimonio', max_length=100, verbose_name='Nombre del Cliente')),
                ('client_role', models.CharField(blank=True, help_text='Cargo o empresa del cliente (ej: "Gerente, Empresa ABC")', max_length=100, verbose_name='Cargo / Empresa')),
                ('client_photo', cloudinary.models.CloudinaryField(blank=True, help_text='Foto de la persona que da el testimonio (opcional)', max_length=255, null=True, verbose_name='testimonial_photo')),
                ('testimonial', models.TextField(help_text='Texto completo del testimonio', verbose_name='Testimonio')),
                ('rating', models.IntegerField(default=5, help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1, message='El rating mínimo es 1 estrella'), django.core.validators.MaxValueValidator(5, message='El rating máximo es 5 estrellas')], verbose_name='Rating')),
                ('is_active', models.BooleanField(default=True, help_text='Si está inactivo, no se mostrará en el sitio', verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, help_text='Testimonios destacados se muestran primero', verbose_name='Destacado')),
                ('client', models.ForeignKey(help_text='Cliente al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['client', '-is_featured', '-rating', '-created_at'],
                'indexes': [models.Index(fields=['client', 'is_active', 'is_featured'], name='website_tes_client__aa6e36_idx')],
            },
        ),
    ]
