# Generated by Django 5.2.6 on 2025-12-09 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, help_text='Asunto del mensaje', max_length=300)),
                ('message', models.TextField(help_text='Mensaje del contacto')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('read', 'Leído'), ('replied', 'Respondido'), ('spam', 'Spam')], default='new', max_length=20)),
                ('source', models.CharField(default='website', help_text='Origen: website, landing, form, etc.', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP del visitante', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Navegador del visitante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_submissions', to='tenants.client')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='website_con_client__b83d03_idx'), models.Index(fields=['client', '-created_at'], name='website_con_client__757ba2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero / Banner Principal'), ('about', 'Sobre Nosotros'), ('services', 'Servicios (Intro)'), ('features', 'Características'), ('testimonials', 'Testimonios (Intro)'), ('contact', 'Contacto (Intro)'), ('cta', 'Call to Action'), ('footer', 'Footer / Pie de Página')], help_text='Tipo de sección (predefinido)', max_length=50)),
                ('title', models.CharField(help_text='Título principal de la sección', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Subtítulo o tagline (opcional)', max_length=300)),
                ('image', models.ImageField(blank=True, help_text='Imagen de la sección (opcional)', null=True, upload_to='sections/%Y/%m/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, help_text='¿Mostrar esta sección en el sitio?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tenants.client')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['order', 'section_type'],
                'indexes': [models.Index(fields=['client', 'section_type'], name='website_sec_client__da3144_idx'), models.Index(fields=['client', 'is_active'], name='website_sec_client__6e63e8_idx')],
                'unique_together': {('client', 'section_type')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del servicio', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL amigable (se genera automáticamente)', max_length=250)),
                ('description', models.TextField(help_text='Descripción breve del servicio')),
                ('icon', models.CharField(default='⚡', help_text="Emoji o clase de icono (ej: 'fa-bolt')", max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Imagen del servicio (opcional)', null=True, upload_to='services/%Y/%m/')),
                ('price_text', models.CharField(blank=True, help_text="Ej: 'Desde $50.000' o 'Consultar precio'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, help_text='¿Mostrar este servicio?')),
                ('is_featured', models.BooleanField(default=False, help_text='¿Es un servicio destacado?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tenants.client')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['client', 'slug'], name='website_ser_client__de6c2e_idx'), models.Index(fields=['client', 'is_active'], name='website_ser_client__0d75ab_idx'), models.Index(fields=['client', 'is_featured'], name='website_ser_client__83c383_idx')],
                'unique_together': {('client', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Nombre del cliente que da el testimonio', max_length=200)),
                ('company', models.CharField(blank=True, help_text='Empresa del cliente (opcional)', max_length=200)),
                ('position', models.CharField(blank=True, help_text='Cargo del cliente (opcional)', max_length=200)),
                ('content', models.TextField(help_text='El testimonio en sí')),
                ('avatar', models.ImageField(blank=True, help_text='Foto del cliente (opcional)', null=True, upload_to='testimonials/%Y/%m/')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 estrellas'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], default=5, help_text='Calificación de 1 a 5 estrellas')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, help_text='¿Mostrar este testimonio?')),
                ('is_featured', models.BooleanField(default=False, help_text='¿Destacar en home?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='tenants.client')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['client', 'is_active'], name='website_tes_client__16f995_idx'), models.Index(fields=['client', 'is_featured'], name='website_tes_client__7f8fcf_idx')],
            },
        ),
    ]
