# Generated by Django 5.2.6 on 2025-12-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción larga (para about, generic, etc.)'),
        ),
    ]
