# Generated by Django 5.2.6 on 2025-12-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_add_section_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='full_description',
            field=models.TextField(blank=True, default='', help_text='Descripción completa del servicio'),
        ),
    ]
