# Generated by Django 5.2.6 on 2026-01-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_add_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero / Banner Principal'), ('about', 'Sobre Nosotros'), ('service', 'Servicio Individual'), ('contact', 'Contacto')], help_text='Tipo de sección (predefinido)', max_length=50),
        ),
    ]
