# Generated by Django 5.2.6 on 2026-01-13 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_migrate_to_cloudinary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
