# Generated by Django 5.2.6 on 2026-03-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_delete_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, default='⚡', help_text="Emoji o clase de icono (ej: 'fa-bolt')", max_length=50),
        ),
    ]
