# Generated by Django 5.2.6 on 2026-03-05 02:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='source',
            field=models.CharField(default='website', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen de la sección → Cloudinary: tenants/{slug}/sections/', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen del servicio → Cloudinary: tenants/{slug}/services/', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
