# Generated by Django 5.2.6 on 2026-03-21 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_contactsubmission_ip_address_and_more'),
        ('website', '0009_contactsubmission_form_source_spam'),
    ]

    operations = [
    ]
