# Generated by Django 5.2.6 on 2026-03-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_merge_20260321_0125'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='website_con_client__3f6c0d_idx',
            old_name='website_con_client_spam_idx',
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='is_spam',
            field=models.BooleanField(default=False, help_text='Marcado como spam por el honeypot. Conservado para auditoría.'),
        ),
    ]
