# Generated by Django 5.2.6 on 2026-03-31 22:20

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_alter_clientsettings_auto_purge_enabled_and_more'),
        ('website', '0011_rename_website_con_client_spam_idx_website_con_client__3f6c0d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Título opcional para la imagen (visible en modo galería)', max_length=200, verbose_name='Título')),
                ('caption', models.TextField(blank=True, help_text='Descripción breve visible bajo la imagen o en overlay', verbose_name='Descripción')),
                ('image', cloudinary.models.CloudinaryField(help_text='Imagen → Cloudinary: tenants/{slug}/gallery/', max_length=255, verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(default=0, help_text='Menor número aparece primero', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, help_text='Desactiva para ocultar esta imagen sin eliminarla', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='tenants.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Galería de Imágenes',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['client', 'is_active'], name='website_gal_client__f6fb24_idx'), models.Index(fields=['client', 'order'], name='website_gal_client__8848fc_idx')],
            },
        ),
    ]
