# Generated by Django 5.2.6 on 2026-04-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_add_enable_gallery'),
        ('website', '0012_add_galleryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['gallery_type', 'order', 'created_at'], 'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes del sitio'},
        ),
        migrations.RemoveIndex(
            model_name='galleryitem',
            name='website_gal_client__f6fb24_idx',
        ),
        migrations.RemoveIndex(
            model_name='galleryitem',
            name='website_gal_client__8848fc_idx',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='gallery_type',
            field=models.CharField(choices=[('hero', 'Portada del sitio'), ('gallery', 'Galería de imágenes')], default='gallery', help_text='Portada: imagen de fondo del hero. Galería: sección de imágenes.', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Imagen seed entregada al provisionar el sitio. Siempre disponible como fallback. No eliminable desde el dashboard.', verbose_name='Imagen por defecto'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='caption',
            field=models.TextField(blank=True, help_text='Descripción breve visible bajo la imagen o en overlay.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desactiva para ocultar esta imagen sin eliminarla.', verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Menor número aparece primero.', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='title',
            field=models.CharField(blank=True, help_text='Título opcional visible en la galería o sobre la imagen.', max_length=200, verbose_name='Título'),
        ),
        migrations.AddIndex(
            model_name='galleryitem',
            index=models.Index(fields=['client', 'gallery_type', 'is_active'], name='website_gal_client__ea3fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryitem',
            index=models.Index(fields=['client', 'gallery_type', 'order'], name='website_gal_client__1891af_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryitem',
            index=models.Index(fields=['client', 'is_default'], name='website_gal_client__114a08_idx'),
        ),
    ]
