# Generated by Django 5.2.6 on 2026-04-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_galleryitem_add_type_and_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero / Banner Principal'), ('about', 'Sobre Nosotros'), ('service', 'Servicio Individual'), ('contact', 'Contacto'), ('gallery', 'Galería de Imágenes')], help_text='Tipo de sección (predefinido)', max_length=50),
        ),
    ]
