# Generated by Django 5.2.6 on 2026-04-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_section_add_gallery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='cta_text',
            field=models.CharField(blank=True, help_text='Ej: "Solicitar cotización", "Ver servicios". Solo aplica en portada.', max_length=100, verbose_name='Texto del botón'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='cta_url',
            field=models.CharField(blank=True, help_text='Ancla interna: "#contacto". URL relativa: "/servicios/". URL externa: "https://...". Vacío = botón no se renderiza.', max_length=200, verbose_name='URL del botón'),
        ),
    ]
