# Generated by Django 5.2.6 on 2026-04-10 04:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_section_add_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='background_image',
        ),
        migrations.AddField(
            model_name='section',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen de fondo del hero → Cloudinary: tenants/{slug}/sections/', max_length=255, null=True, verbose_name='background_image'),
        ),
    ]
