# Generated by Django 5.2.6 on 2026-04-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_section_add_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slot_key',
            field=models.CharField(choices=[('hero', 'Hero / Portada'), ('gallery', 'Galería de imágenes'), ('profile', 'Perfil / Profesionales'), ('empty', 'Sin overlay')], default='empty', help_text='Define qué slot de contenido se renderiza sobre las imágenes.', max_length=50),
        ),
    ]
