# Generated by Django 5.2.6 on 2026-08-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_clientsettings_accent_color'),
        ('website', '0018_section_add_slot_key'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='service',
            name='website_ser_client__0d75ab_idx',
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['client', 'is_active', 'order'], name='website_ser_client__40483c_idx'),
        ),
    ]
