# Generated by Django 5.2.6 on 2026-08-25 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0025_migrate_theme_template_values'),
        ('website', '0019_remove_service_website_ser_client__0d75ab_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['section', 'service', 'order', 'created_at'], 'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes del sitio'},
        ),
        migrations.RemoveIndex(
            model_name='galleryitem',
            name='website_gal_client__ea3fe4_idx',
        ),
        migrations.RemoveIndex(
            model_name='galleryitem',
            name='website_gal_client__1891af_idx',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='section',
            field=models.ForeignKey(blank=True, help_text='El rol de la imagen (portada, galería, etc.) sale del section_type de esta sección.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='website.section', verbose_name='Sección'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Foto de la galería de este servicio.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='website.service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='gallery_type',
            field=models.CharField(blank=True, default='gallery', max_length=20),
        ),
        migrations.AddIndex(
            model_name='galleryitem',
            index=models.Index(fields=['client', 'section', 'is_active'], name='website_gal_client__29c9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryitem',
            index=models.Index(fields=['client', 'service', 'is_active'], name='website_gal_client__7dcea2_idx'),
        ),
    ]
