# Generated by Django 5.2.6 on 2026-08-25 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_migrate_gallery_type_to_owner_fks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='gallery_type',
        ),
    ]
